# Generated by Django 2.1.5 on 2019-01-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirection',
            name='redirection',
            field=models.CharField(default='https://google.es', max_length=500),
            preserve_default=False,
        ),
    ]
