# Generated by Django 2.1.5 on 2019-01-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirections', '0002_redirection_redirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirection',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
